DEFINE TABLE DBT_DCM_DEMO.RAW{{ env_suffix }}.CLIENTS (
    CLIENT_ID NUMBER NOT NULL,
    CLIENT_NAME VARCHAR(200),
    REGION VARCHAR(50),
    EMPLOYEE_COUNT NUMBER,
    PLAN_TYPE VARCHAR(50),
    ONBOARDED_AT TIMESTAMP_NTZ
)
CHANGE_TRACKING = TRUE
COMMENT = 'CheckPay client accounts'
DATA_RETENTION_TIME_IN_DAYS = {{ data_retention_days }};

DEFINE TABLE DBT_DCM_DEMO.RAW{{ env_suffix }}.PAYROLL_RUNS (
    PAYROLL_RUN_ID NUMBER NOT NULL,
    CLIENT_ID NUMBER NOT NULL,
    RUN_DATE DATE,
    PAY_PERIOD_START DATE,
    PAY_PERIOD_END DATE,
    TOTAL_GROSS_PAY NUMBER(15,2),
    TOTAL_NET_PAY NUMBER(15,2),
    CHECK_COUNT NUMBER,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    PROCESSED_AT TIMESTAMP_NTZ,
    PAYMENT_METHOD VARCHAR(50)
)
CHANGE_TRACKING = TRUE
COMMENT = 'CheckPay payroll processing runs'
DATA_RETENTION_TIME_IN_DAYS = {{ data_retention_days }};
