WITH source AS (
    SELECT * FROM {{ source('raw', 'clients') }}
)

SELECT
    CLIENT_ID,
    TRIM(CLIENT_NAME) AS CLIENT_NAME,
    UPPER(REGION) AS REGION,
    EMPLOYEE_COUNT,
    UPPER(PLAN_TYPE) AS PLAN_TYPE,
    ONBOARDED_AT
FROM source
WHERE CLIENT_ID IS NOT NULL
